import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
	title: "Cinemania",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="dark">
			<body className="dark:bg-background dark:text-text ">
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	);
}
