import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/context/ThemeContext";

export const metadata: Metadata = {
	title: "Cinemania",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="dark:bg-background dark:text-text ">
				<ThemeProvider>
					<Navbar />
					<main className="dark:bg-background dark:text-text ">{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
